# Generated by Django 4.0.1 on 2022-01-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='assigned_role',
        ),
    ]
