# Generated by Django 4.0.1 on 2022-03-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_assigned_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
