# Generated by Django 4.0.1 on 2022-03-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_tickets',
        ),
    ]
