# Generated by Django 4.0.1 on 2022-03-26 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_remove_project_assigned_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(null=True, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
