# Generated by Django 4.0.1 on 2022-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.ManyToManyField(related_name='assigned_comments', to='tickets.Comment'),
        ),
    ]
