# Generated by Django 4.0.1 on 2022-03-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_assigned_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket'),
        ),
    ]
