# Generated by Django 4.0.1 on 2022-03-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_description_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='attachment',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('parent_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='tickets.ticket')),
            ],
        ),
    ]
