# Generated by Django 4.0.1 on 2022-03-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_remove_ticket_attachment_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='parent_ticket',
        ),
    ]
