# Generated by Django 4.0.1 on 2022-03-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_attachment_parent_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='parent_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='tickets.ticket'),
        ),
    ]
