# Generated by Django 4.0.1 on 2022-03-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_attachment_parent_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='parent_ticket',
        ),
    ]
