# Generated by Django 4.0.1 on 2022-03-13 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_attachment_parent_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='parent_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='tickets.ticket'),
        ),
    ]
