# Generated by Django 4.0.1 on 2022-03-14 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_attachment_parent_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
