# Generated by Django 4.0.1 on 2022-03-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_historicalticket_parent_ticket_ticket_parent_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalticket',
            old_name='parent_ticket',
            new_name='parent_project',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='parent_ticket',
            new_name='parent_project',
        ),
    ]
