# Generated by Django 4.0.1 on 2022-03-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_ticket_parent_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalticket',
            old_name='parent_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='parent_project',
            new_name='project',
        ),
    ]
