# Generated by Django 4.0.1 on 2022-03-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_rename_parent_project_historicalticket_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='update_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='update_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
