# Generated by Django 4.0.1 on 2022-03-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_historicalticket_update_time_ticket_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='update_time',
        ),
    ]
